### ISSUE TITLE
Publish a new version to Maven Central under the new name

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-sdk-android#43]
- The latest version in Maven Central is `1.2.0`, while the latest git tag is `1.3.0`. 
- The project name has changed to `loopback-sdk-android` in the meantime.
- API docs shows version 1.4.1 in the menu and 1.3.1-SNAPSHOT in the content.

A new version release will fix all three issues in one go.

Once the new version is released, we need to update the Confluence documentation too ([link](http://docs.strongloop.com/display/LB/Android+SDK#AndroidSDK-WorkingwiththeSDK)).

**Tasks**
- [x] Update API docs in git
- [x] Release to Maven
- [x] Release to npmjs.org
- [x] fix apidocs website - it is not picking the npm package correctly
- [x] verify that v1.5.0 can be installed from Maven via gradle
- [x] upload the bundle to CDN (Chandrika)
  -  Upload http://artifactory.strongloop.com:8081/artifactory/repo/com/strongloop/loopback-sdk-android/1.5.0/loopback-sdk-android-1.5.0-eclipse-bundle.zip to Rackspace CDN 
  - Update the download link in http://docs.strongloop.com/display/LB/Android+SDK
